### ISSUE TITLE
Tools

### ISSUE THREAD

**Issue by Steellgold** [Itzdvbravo/CustomisedBravo#1]
How do we have to display the item, like for example a sword, and not an ingot (When we look at F5) ?

**Comment by Itzdvbravo** [comment]
I never knew they look different, Never tested, will try to figure it now! lol :p

**Comment by Steellgold** [comment]
I send you a screenshot, when i have the time

**Comment by Itzdvbravo** [comment]
> I send you a screenshot, when i have the time

I have already seen it just now, you don't need to.

**Comment by Steellgold** [comment]
Okay let me know if you find the solution

**Comment by Steellgold** [comment]
And, if i set a durability in item (with a extends Sword and a getMaxDurability function), the durability bar not show

**Comment by DasEpicDv** [comment]
Aight! I am the new repo owner, and i'll check soon!

**Comment by Steellgold** [comment]
Okay

**Comment by DasEpicDv** [comment]
> And, if i set a durability in item (with a extends Sword and a getMaxDurability function), the durability bar not show

I think that's client sided..

**Comment by PiloudeDakar** [comment]
I think if you add an extends with the type of item class and no directly item class this solve your problem

**Comment by Steellgold** [comment]
for the item texture in hand ?

**Comment by PiloudeDakar** [comment]
No this I don't know

**Comment by PiloudeDakar** [comment]
Perhaps is a function (setDurabilityViewable)
